name: 'ReportGenerator'
author: 'danielpalme'
description: 'Creates coverage reports from tools like OpenCover, dotCover, Visual Studio, NCover, Cobertura, JaCoCo, Clover, gcov or lcov'
inputs:
  reports:
    description: 'The coverage reports that should be parsed (separated by semicolon). Globbing is supported.'
    required: true
    default: 'coverage.xml'
  targetdir:
    description: 'The directory where the generated report should be saved.'
    required: true
    default: 'coveragereport'
  reporttypes:
    description: 'The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary'
    required: false
    default: 'HtmlInline;Cobertura'
  sourcedirs:
    description: 'Optional directories which contain the corresponding source code (separated by semicolon). The source directories are used if coverage report contains classes without path information.'
    required: false
    default: ''
  historydir:
    description: 'Optional directory for storing persistent coverage information. Can be used in future reports to show coverage evolution.'
    required: false
    default: ''
  plugins:
    description: 'Optional plugin files for custom reports or custom history storage (separated by semicolon).'
    required: false
    default: ''
  assemblyfilters:
    description: 'Optional list of assemblies that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.'
    required: false
    default: '+*'
  classfilters:
    description: 'Optional list of classes that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.'
    required: false
    default: '+*'
  filefilters:
    description: 'Optional list of files that should be included or excluded in the report. Exclusion filters take precedence over inclusion filters. Wildcards are allowed.'
    required: false
    default: '+*'
  verbosity:
    description: 'The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off'
    required: false
    default: 'Info'
  title:
    description: 'Optional title.'
    required: false
    default: ''
  tag:
    description: 'Optional tag or build version.'
    required: false
    default: '${{ github.run_number }}_${{ github.run_id }}'
  customSettings:
    description: 'Optional custom settings (separated by semicolon). See: https://github.com/danielpalme/ReportGenerator/wiki/Settings'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bar-chart-2'  
  color: 'green'
